"""initial

Revision ID: 824e6a858fd9
Revises: 
Create Date: 2026-05-02 18:20:15.533197
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '824e6a858fd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gmail_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gmail_email', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('history_id', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('source_email_id', sa.String(length=255), nullable=True),
    sa.Column('source_email_subject', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invoices_user_date', 'invoices', ['user_id', 'invoice_date'], unique=False)
    op.create_index('idx_invoices_user_status', 'invoices', ['user_id', 'status'], unique=False)
    op.create_table('processed_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('is_invoice', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_emails_lookup', 'processed_emails', ['user_id', 'gmail_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_processed_emails_lookup', table_name='processed_emails')
    op.drop_table('processed_emails')
    op.drop_index('idx_invoices_user_status', table_name='invoices')
    op.drop_index('idx_invoices_user_date', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('gmail_connections')
    op.drop_table('users')
    # ### end Alembic commands ###
